### ISSUE TITLE
Missing dependency when installing

### ISSUE THREAD

**Issue by javiquinte** [larean/obsinfo#6]
The module `gitlab` is missing at installation time. As soon as `obsinfo-makeSTATIONXML` is run the following error occurs.

```
$ obsinfo-makeSTATIONXML -h
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/obsinfo-makeSTATIONXML", line 5, in <module>
    from obsinfo.main.makeStationXML import main
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/obsinfo/main/makeStationXML.py", line 15, in <module>
    from ..network import (Network)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/obsinfo/network/__init__.py", line 1, in <module>
    from .network import Network
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/obsinfo/network/network.py", line 19, in <module>
    from ..obsMetadata.obsmetadata import (ObsMetadata)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/obsinfo/obsMetadata/__init__.py", line 1, in <module>
    from .obsmetadata import ObsMetadata
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/obsinfo/obsMetadata/obsmetadata.py", line 24, in <module>
    from ..misc import yamlref
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/obsinfo/misc/yamlref.py", line 22, in <module>
    from ..misc.remoteGitLab import gitLabFile
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/obsinfo/misc/remoteGitLab.py", line 1, in <module>
    import gitlab
ModuleNotFoundError: No module named 'gitlab'
```

**Comment by WayneCrawford** [comment]
Yes, I noticed this as well.  `gitlab` should be added to the list of `install_requires` in the `setup.cfg` file.
In the meantime, you can run `pip install gitlab` in your obsinfo environment

**Comment by larean** [comment]
Added to setup.py
